Develop
CastFX/pps1819 pull request #3
Opened 2020-03-22 19:38 UTC by deividvd

# Description

Most part of the logic is implemented: Checkmate should be the only things that doesn't work. 

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Basically the Fool's Checkmate has been set and the program recognize the check.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-03-23 00:03 UTC, CastFX requested changes
Left a couple of requested changes, reviewed with Maicol

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/ChessGame.scala
> +    moveValidator.computeMoveErrors(move, player) match {
`computeMoveErrors`doesn't mean anything, a better name could be `validate`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +  def computeMoveErrors(move: String, player: Color): Either[String, ValidMove] =
Use `Validation[String. ValidMove]
`
`computeMoveErrors`doesn't mean anything, a better name could be `validate`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/ChessGame.scala
> +  def moveAftermath(): Either[String, ChessGame] =
If `moveAftermath()` is only used in the tests it should not be part of the main ChessGame API
Also the name doesn't suggest what it's doing.

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/ChessGame.scala
> +    /*if (checkValidator.controlCheckMate(player))
Useless comments should be removed

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/board/Board.scala
> +    val pieces: Map[Position, Piece]
val here is useless, case class fields are already val by default

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/board/Position.scala
> +    else false
<s>def isAdjacentTo(pos: Position): Boolean = Set(up, down, left, right, upRight, upLeft, downRight, downLeft) contains pos</s>

EDIT: 
`def isAdjacentTo(pos: Position): Boolean = adjacentPositions contains pos`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/board/Position.scala
> +  def computeAdjacentPos(): List[Position] =
`lazy var adjacentPositions: Set[Positon] = Set(up, down, left, right, upRight, upLeft, downRight, downLeft)
`
(and goes at line 21)

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +  def controlCheckOnTurnEnd(move: ValidMove, player: Color): Boolean = {
`isKingInCheckAfter` instead of `controlCheckOnTurnEnd`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +  def controlCheck(player: Color): Boolean = {
`isKingInCheck` instead of `controlCheck`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +  def controlCheckMate(player: Color): Boolean = {
`isCheckmate` instead of `controlCheckMate`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +    val boardCopy = board.copy()(move)
`board(move)` is already a "copy" of board, no need for `.copy()`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +  private def filterKingPos(board: Board, player: Color): Position =
This method filters the board whenever it's called.
Would be better to have this inside Board.scala
`lazy val kingPos: Position = pieces filter 
`
Also this method fails if there is no King

this would be better placed inside Board.scala

```
  lazy val kingPositions: Map[Color, Position] = pieces collect {
    case (pos, Piece(color, King)) => (color -> pos)
  }
  def kingPositionOf(color: Color): Option[Position] = kingPositions get color
```

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/CheckValidator.scala
> +  private def kingCanBeCaptured(board: Board, kingPos: Position, player: Color): Boolean =
`board` parameter is overriding the `board` field of the case class
is `player` parameter the moving one or the captured one? Use a better name

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +  private def computeMoveFormat(move: String): Either[String, (Position, Position)] =
Use `Validation[String, ValidMove]`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +  def computeShiftError(from: Position, to: Position, player: Color): Either[String, Piece] =
Use `Validation[String, ValidMove]`
`validateShift` would be a better name

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +          case Left(errorMsg) => Left(errorMsg)
```
case Right([...]) => [...]
case _ => _ 
```

instead of `case Left(errorMsg) => Left(errorMsg)`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +        if (playerPiece.color == player.other) Left("Can't move an enemy piece")
=== instead of ==

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/pieces/Piece.scala
> +    val colDistanceInt = start colDistanceAbs end
No need to specify the type in the variable name
`colDistance: Int = start colDistanceAbs end`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/pieces/Piece.scala
> +        val rowDistanceInt = start rowDistanceAbs end
rowDistanceInt from a method called rowDistanceAbs?
Also no need to specify the type in the variable name
`rowDistance: Int = start rowDistanceAbs end`

2020-03-23 00:03 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/pieces/Piece.scala
> +        val rowDistanceInt = end rowDistanceInt start
no need to specify the type in the variable name
`rowDistance: Int = end rowDistanceInt start`

2020-03-23 16:08 UTC, deividvd commented on core/src/main/scala/it/scalachess/core/logic/MoveValidator.scala
> +        if (playerPiece.color == player.other) Left("Can't move an enemy piece")
since Color is an instance of 'object', it does not implements the metod ===

2020-03-24 00:27 UTC, CastFX requested changes

2020-03-24 00:27 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/GameStatus.scala
> +final case object WhiteWin extends GameStatus
Win(player: Color) instead of two different classes

2020-03-24 00:27 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/board/Position.scala
>    /**
No need for Option[Position]
` lazy val adjacentPositions: Set[Position] =
    Set(left, right, down, up, downLeft, downRight, upLeft, upRight).flatten`

2020-03-24 00:27 UTC, CastFX commented on core/src/main/scala/it/scalachess/core/board/Position.scala
> +  def isAdjacentTo(pos: Position): Boolean = adjacentPositions.exists(_.contains(pos))
`def isAdjacentTo(pos: Position): Boolean = adjacentPositions contains pos`

2020-03-26 01:10 UTC, CastFX approved these changes

2020-03-26 08:21 UTC, ZeroMaicol approved these changes

2020-03-26 08:21 UTC, merged